"""Add prompt template system - templates and usage tracking

Revision ID: 9e03476c50fb
Revises: a9da2f22fbec
Create Date: 2025-07-14 14:02:05.944412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e03476c50fb'
down_revision: Union[str, Sequence[str], None] = 'a9da2f22fbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('rendered_prompt', sa.Text(), nullable=False),
    sa.Column('variables_used', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('corrections_count', sa.Integer(), nullable=True),
    sa.Column('context_turns_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('evaluations', sa.Column('prompt_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'evaluations', 'prompt_templates', ['prompt_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'prompt_template_id')
    op.drop_table('prompt_usage')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
