"""Add function_template_id to evaluations

Revision ID: add_func_template_id
Revises: add_business_insights_field
Create Date: 2025-07-23 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_func_template_id'
down_revision = 'add_business_insights_field'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('function_template_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key('fk_evaluations_function_template', 'evaluations', 'function_prompt_templates', ['function_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_evaluations_function_template', 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'function_template_id')
    # ### end Alembic commands ###